DROP TABLE IF EXISTS Aluguel CASCADE;
DROP TABLE IF EXISTS Livro CASCADE;
DROP TABLE IF EXISTS Usuario CASCADE;

CREATE TABLE Endereco (
    ID_Endereco SERIAL PRIMARY KEY,
    CEP VARCHAR(9) NOT NULL,
    Estado VARCHAR(50) NOT NULL,
    Cidade VARCHAR(50) NOT NULL,
    Rua VARCHAR(50) NOT NULL,
    Numero INTEGER NOT NULL
);

CREATE TABLE Usuario (
    CPF VARCHAR(11) PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Sobrenome VARCHAR(50) NOT NULL,
    Email VARCHAR(100) NOT NULL,
    Telefone VARCHAR(15) NOT NULL,
    ID_Endereco INTEGER NOT NULL,
    FOREIGN KEY (ID_Endereco) REFERENCES Endereco(ID_Endereco)
);

CREATE TABLE Titulo (
    ID_titulo SERIAL PRIMARY KEY,
    Titulo VARCHAR(100) NOT NULL,
    Autor VARCHAR(50) NOT NULL,
    Editora VARCHAR(50) NOT NULL,
    Ano INTEGER NOT NULL
);

CREATE TABLE Livro (
    ISBN VARCHAR(13) PRIMARY KEY,
    Edicao VARCHAR(10) NOT NULL,
    Qntd_total INTEGER NOT NULL,
    Qntd_disponivel INTEGER NOT NULL,
    ID_titulo INTEGER NOT NULL,
    FOREIGN KEY (ID_titulo) REFERENCES Titulo(ID_titulo)
);

CREATE TABLE Aluguel (
    ID_aluguel SERIAL PRIMARY KEY,
    Data_aluguel DATE NOT NULL,
    Data_devolucao DATE NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    ISBN VARCHAR(13) NOT NULL,
    FOREIGN KEY (CPF) REFERENCES Usuario(CPF),
    FOREIGN KEY (ISBN) REFERENCES Livro(ISBN)
);
